name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  integtration-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Debug
      run: ls -R
    - name: Run Unit Tests
      run: cargo test -- --test-threads=1 || cargo test -- --test-threads=1
    - name: Run Integration Tests
      run: cargo run --bin tests || cargo run --bin tests
